name: Update PR Branch
on:
  push:
    branches: ['main']
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
      - name: Update branch
        uses: adRise/update-pr-branch@v0.10
        with:
          token: ${{ steps.app-token.outputs.token }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: true
          require_auto_merge_enabled: true
          sort: 'created'